# Generated by Django 3.2.3 on 2021-06-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='wake_up_time',
        ),
    ]
